# Generated by Django 3.0.4 on 2020-03-10 00:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuuidclass',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6dafb4a6-612b-4620-91ad-cb52785959c3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
