# Generated by Django 3.0.4 on 2020-03-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200309_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='solution',
            new_name='_solution',
        ),
    ]
