# Generated by Django 3.0.4 on 2020-03-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200309_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='displayWord',
            field=models.CharField(default='----------', max_length=10),
        ),
    ]
