# Generated by Django 3.0.4 on 2020-03-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_word_displayword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='displayWord',
            field=models.CharField(default='__________', max_length=10),
        ),
    ]
