# Generated by Django 3.0.4 on 2020-03-10 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20200309_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
